### ISSUE TITLE
[Bug] Vans rank 2 effect not reflected

### ISSUE THREAD

**Issue by keplerk** [nick-stanley/fallout-4-character-builder#1]
Hi, when vans rank 2 is selected the +2 on perception doesn't seems to be applied, any chance to get a fix ?

Thanks :D

**Comment by nick-stanley** [comment]
Hi @keplerk, while you do get +2 to perception when rank 2 of V.A.N.S is applied, +2 is added to the perception stat, rather than the attribute level required to acquire a perk. For instance, if perception is originally at 1, upgrading the V.A.N.S. perk to rank 2 does not unlock the perception level 3 "Awareness" perk. The character builder is more to allow you to plan which perks you want to take at which level, rather than what your stats are for each S.P.E.C.I.A.L attribute, which is why clothing that gives you boosts to different attributes isn't included.

**Comment by keplerk** [comment]
Any plan to release the source ?

**Comment by nick-stanley** [comment]
No plans to release the source yet, although I might rewrite it and release that. Does my reply above make sense?
